"use strict";

define(["artifact/js/FiringArc", "artifact/js/Maneuver", "artifact/js/Range", "artifact/js/ShipAction", "artifact/js/ShipBase"],
   function(FiringArc, Maneuver, Range, ShipAction, ShipBase)
   {
      var Ship = {
         AGGRESSOR: "aggressor",
         ALPHA_CLASS_STAR_WING: "alphaclassstarwing",
         ARC_170: "arc170",
         ATTACK_SHUTTLE: "attackshuttle",
         AUZITUCK_GUNSHIP: "auzituckgunship",
         A_WING: "awing",
         B_SF_17_BOMBER: "bsf17bomber",
         B_WING: "bwing",
         E_WING: "ewing",
         FIRESPRAY_31: "firespray31",
         G_1A_STARFIGHTER: "g1astarfighter",
         HWK_290: "hwk290",
         JUMP_MASTER_5000: "jumpmaster5000",
         KIHRAXZ_FIGHTER: "kihraxzfighter",
         K_WING: "kwing",
         LAMBDA_CLASS_SHUTTLE: "lambdaclassshuttle",
         LANCER_CLASS_PURSUIT_CRAFT: "lancerclasspursuitcraft",
         M12_L_KIMOGILA_FIGHTER: "m12lkimogilafighter",
         M3_A_INTERCEPTOR: "m3ainterceptor",
         PROTECTORATE_STARFIGHTER: "protectoratestarfighter",
         QUADJUMPER: "quadjumper",
         SCURRG_H_6_BOMBER: "scurrgh6bomber",
         SHEATHIPEDE_CLASS_SHUTTLE: "sheathipedeclassshuttle",
         STAR_VIPER: "starviper",
         TIE_ADVANCED: "tieadvanced",
         TIE_ADVANCED_PROTOTYPE: "tieadvprototype",
         TIE_AGGRESSOR: "tieaggressor",
         TIE_BOMBER: "tiebomber",
         TIE_DEFENDER: "tiedefender",
         TIE_FIGHTER: "tiefighter",
         TIE_FO_FIGHTER: "tiefofighter",
         TIE_INTERCEPTOR: "tieinterceptor",
         TIE_PHANTOM: "tiephantom",
         TIE_PUNISHER: "tiepunisher",
         TIE_SF_FIGHTER: "tiesffighter",
         TIE_SILENCER: "tiesilencer",
         TIE_STRIKER: "tiestriker",
         T_70_X_WING: "t70xwing",
         UPSILON_CLASS_SHUTTLE: "upsilonclassshuttle",
         U_WING: "uwing",
         VCX_100: "vcx100",
         VT_49_DECIMATOR: "vt49decimator",
         X_WING: "xwing",
         YT_1300: "yt1300",
         YT_2400: "yt2400",
         YV_666: "yv666",
         Y_WING: "ywing",
         Z_95_HEADHUNTER: "z95headhunter",

         // Huge ships.
         C_ROC_CRUISER: "cRocCruiser",
         CR90_CORVETTE: "cr90Corvette",
         GOZANTI_CLASS_CRUISER: "gozantiClassCruiser",
         GR_75_MEDIUM_TRANSPORT: "gr75MediumTransport",
         RAIDER_CLASS_CORVETTE: "raiderClassCorvette",

         properties:
         {
            "aggressor":
            {
               name: "Aggressor",
               description: "An Aggressor.",
               primaryWeaponValue: 3,
               agilityValue: 3,
               hullValue: 4,
               shieldValue: 4,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.BANK_LEFT_3_EASY, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_EASY, Maneuver.SEGNORS_LOOP_LEFT_3_HARD, Maneuver.SEGNORS_LOOP_RIGHT_3_HARD,
        Maneuver.KOIOGRAN_TURN_4_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BOOST, ShipAction.EVADE],
               wave: "6",
               wikiUrl: "http://xwing-miniatures.wikia.com/wiki/IG-2000_Expansion_Pack",
               key: "aggressor",
            },
            "alphaclassstarwing":
            {
               name: "Alpha-class Star Wing",
               primaryWeaponValue: 2,
               agilityValue: 2,
               hullValue: 4,
               shieldValue: 3,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.RELOAD, ShipAction.SLAM, ShipAction.TARGET_LOCK],
               wave: "12",
               key: "alphaclassstarwing",
            },
            "arc170":
            {
               name: "ARC-170",
               description: "An ARC-170.",
               primaryWeaponValue: 2,
               agilityValue: 1,
               hullValue: 6,
               shieldValue: 3,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               auxiliaryFiringArcKey: FiringArc.AFT,
               maneuverKeys: [Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_HARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_HARD, Maneuver.KOIOGRAN_TURN_4_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "9",
               key: "arc170",
            },
            "attackshuttle":
            {
               name: "Attack Shuttle",
               primaryWeaponValue: 3,
               agilityValue: 2,
               hullValue: 2,
               shieldValue: 2,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_HARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_HARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_HARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.EVADE, ShipAction.FOCUS],
               wave: "8",
               key: "attackshuttle",
            },
            "auzituckgunship":
            {
               name: "Auzituck Gunship",
               primaryWeaponValue: 3,
               agilityValue: 1,
               hullValue: 6,
               shieldValue: 3,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               auxiliaryFiringArcKey: FiringArc.FULL_AFT,
               maneuverKeys: [Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD,
        Maneuver.STRAIGHT_5_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.REINFORCE],
               wave: "11",
               key: "auzituckgunship",
            },
            "awing":
            {
               name: "A-Wing",
               primaryWeaponValue: 2,
               agilityValue: 3,
               hullValue: 2,
               shieldValue: 2,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_EASY, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_EASY,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_EASY,
        Maneuver.STRAIGHT_5_EASY, Maneuver.KOIOGRAN_TURN_5_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BOOST, ShipAction.EVADE],
               wave: "2",
               key: "awing",
            },
            "bsf17bomber":
            {
               name: "B/SF-17 Bomber",
               primaryWeaponValue: 2,
               agilityValue: 1,
               hullValue: 9,
               shieldValue: 3,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               isPrimaryWeaponTurret: true,
               maneuverKeys: [Maneuver.STATIONARY_0_HARD,
        Maneuver.TURN_LEFT_1_HARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_HARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "13",
               key: "bsf17bomber",
            },
            "bwing":
            {
               name: "B-Wing",
               primaryWeaponValue: 3,
               agilityValue: 1,
               hullValue: 3,
               shieldValue: 5,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_HARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_HARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD, Maneuver.KOIOGRAN_TURN_2_HARD,
        Maneuver.BANK_LEFT_3_HARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BARREL_ROLL],
               wave: "3",
               key: "bwing",
            },
            "ewing":
            {
               name: "E-Wing",
               primaryWeaponValue: 3,
               agilityValue: 3,
               hullValue: 2,
               shieldValue: 3,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD,
        Maneuver.STRAIGHT_5_STANDARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BARREL_ROLL, ShipAction.EVADE],
               wave: "4",
               key: "ewing",
            },
            "firespray31":
            {
               name: "Firespray-31",
               description: "A Firespray-31.",
               primaryWeaponValue: 3,
               agilityValue: 2,
               hullValue: 6,
               shieldValue: 4,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               auxiliaryFiringArcKey: FiringArc.AFT,
               maneuverKeys: [Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.EVADE],
               wave: "2",
               wikiUrl: "http://xwing-miniatures.wikia.com/wiki/Slave_1_Expansion_Pack",
               key: "firespray31",
            },
            "g1astarfighter":
            {
               name: "G-1A Starfighter",
               primaryWeaponValue: 3,
               agilityValue: 1,
               hullValue: 4,
               shieldValue: 4,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_HARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_HARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.BANK_LEFT_3_HARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_HARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD],
               shipActionKeys: [ShipAction.EVADE, ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "8",
               key: "g1astarfighter",
            },
            "hwk290":
            {
               name: "HWK-290",
               description: "An HWK-290.",
               primaryWeaponValue: 1,
               agilityValue: 2,
               hullValue: 4,
               shieldValue: 1,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.BANK_LEFT_3_HARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "3",
               key: "hwk290",
            },
            "jumpmaster5000":
            {
               name: "JumpMaster 5000",
               primaryWeaponValue: 2,
               agilityValue: 2,
               hullValue: 5,
               shieldValue: 4,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               isPrimaryWeaponTurret: true,
               maneuverKeys: [Maneuver.TURN_LEFT_1_EASY, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_EASY, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD, Maneuver.SEGNORS_LOOP_LEFT_2_STANDARD, Maneuver.SEGNORS_LOOP_RIGHT_2_HARD,
        Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "8",
               key: "jumpmaster5000",
            },
            "kihraxzfighter":
            {
               name: "Kihraxz Fighter",
               primaryWeaponValue: 3,
               agilityValue: 2,
               hullValue: 4,
               shieldValue: 1,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD,
        Maneuver.KOIOGRAN_TURN_5_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "7",
               key: "kihraxzfighter",
            },
            "kwing":
            {
               name: "K-Wing",
               primaryWeaponValue: 2,
               agilityValue: 1,
               hullValue: 5,
               shieldValue: 4,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               isPrimaryWeaponTurret: true,
               maneuverKeys: [Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD

        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.SLAM],
               wave: "7",
               key: "kwing",
            },
            "lambdaclassshuttle":
            {
               name: "Lambda-class Shuttle",
               primaryWeaponValue: 3,
               agilityValue: 1,
               hullValue: 5,
               shieldValue: 5,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.STATIONARY_0_HARD,
        Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_HARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_HARD,
        Maneuver.BANK_LEFT_3_HARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "3",
               key: "lambdaclassshuttle",
            },
            "lancerclasspursuitcraft":
            {
               name: "Lancer-class Pursuit Craft",
               primaryWeaponValue: 3,
               agilityValue: 2,
               hullValue: 7,
               shieldValue: 3,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_STANDARD, Maneuver.BANK_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_EASY, Maneuver.BANK_LEFT_3_EASY, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_EASY, Maneuver.TURN_RIGHT_3_EASY,
        Maneuver.STRAIGHT_4_EASY,
        Maneuver.STRAIGHT_5_STANDARD, Maneuver.KOIOGRAN_TURN_5_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.EVADE, ShipAction.ROTATE_ARC, ShipAction.TARGET_LOCK],
               wave: "9",
               key: "lancerclasspursuitcraft",
            },
            "m12lkimogilafighter":
            {
               name: "M12-L Kimogila Fighter",
               primaryWeaponValue: 3,
               agilityValue: 1,
               hullValue: 6,
               shieldValue: 2,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_HARD, Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD, Maneuver.TURN_RIGHT_1_HARD,
        Maneuver.TURN_LEFT_2_HARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_HARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.KOIOGRAN_TURN_4_HARD],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.FOCUS, ShipAction.RELOAD, ShipAction.TARGET_LOCK],
               wave: "12",
               key: "m12lkimogilafighter",
            },
            "m3ainterceptor":
            {
               name: "M3-A Interceptor",
               primaryWeaponValue: 2,
               agilityValue: 3,
               hullValue: 2,
               shieldValue: 1,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD,
        Maneuver.KOIOGRAN_TURN_5_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BARREL_ROLL, ShipAction.EVADE],
               wave: "6",
               key: "m3ainterceptor",
            },
            "protectoratestarfighter":
            {
               name: "Protectorate Starfighter",
               primaryWeaponValue: 3,
               agilityValue: 3,
               hullValue: 4,
               shieldValue: 0,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_EASY, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_EASY, Maneuver.TALLON_ROLL_LEFT_2_HARD, Maneuver.TALLON_ROLL_RIGHT_2_HARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD,
        Maneuver.STRAIGHT_5_STANDARD],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.BOOST, ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "9",
               key: "protectoratestarfighter",
            },
            "quadjumper":
            {
               name: "Quadjumper",
               primaryWeaponValue: 2,
               agilityValue: 2,
               hullValue: 5,
               shieldValue: 0,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_STANDARD, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD, Maneuver.SEGNORS_LOOP_LEFT_2_HARD, Maneuver.SEGNORS_LOOP_RIGHT_2_HARD,
        Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.FOCUS],
               wave: "10",
               key: "quadjumper",
            },
            "scurrgh6bomber":
            {
               name: "Scurrg H-6 Bomber",
               primaryWeaponValue: 3,
               agilityValue: 1,
               hullValue: 5,
               shieldValue: 5,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_HARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_HARD, Maneuver.TALLON_ROLL_LEFT_3_HARD, Maneuver.TALLON_ROLL_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD,
        Maneuver.STRAIGHT_5_HARD],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "11",
               key: "scurrgh6bomber",
            },
            "sheathipedeclassshuttle":
            {
               name: "Sheathipede-class Shuttle",
               primaryWeaponValue: 2,
               agilityValue: 2,
               hullValue: 4,
               shieldValue: 1,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               auxiliaryFiringArcKey: FiringArc.AFT,
               maneuverKeys: [Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_HARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_HARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_HARD],
               shipActionKeys: [ShipAction.COORDINATE, ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "12",
               key: "sheathipedeclassshuttle",
            },
            "starviper":
            {
               name: "StarViper",
               primaryWeaponValue: 3,
               agilityValue: 3,
               hullValue: 4,
               shieldValue: 1,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.SEGNORS_LOOP_LEFT_3_HARD, Maneuver.SEGNORS_LOOP_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BARREL_ROLL, ShipAction.BOOST],
               wave: "6",
               key: "starviper",
            },
            "t70xwing":
            {
               name: "T-70 X-Wing",
               primaryWeaponValue: 3,
               agilityValue: 2,
               hullValue: 3,
               shieldValue: 3,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD, Maneuver.TALLON_ROLL_LEFT_3_HARD, Maneuver.TALLON_ROLL_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BOOST],
               wave: "0",
               key: "t70xwing",
            },
            "tieadvanced":
            {
               name: "TIE Advanced",
               primaryWeaponValue: 2,
               agilityValue: 3,
               hullValue: 3,
               shieldValue: 2,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD,
        Maneuver.STRAIGHT_5_STANDARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BARREL_ROLL, ShipAction.EVADE],
               wave: "1",
               key: "tieadvanced",
            },
            "tieadvprototype":
            {
               name: "TIE Adv. Prototype",
               primaryWeaponValue: 2,
               agilityValue: 3,
               hullValue: 2,
               shieldValue: 2,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_EASY, Maneuver.BANK_LEFT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_EASY, Maneuver.KOIOGRAN_TURN_4_HARD,
        Maneuver.STRAIGHT_5_STANDARD],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.BOOST, ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "8",
               key: "tieadvprototype",
            },
            "tieaggressor":
            {
               name: "TIE Aggressor",
               primaryWeaponValue: 2,
               agilityValue: 2,
               hullValue: 4,
               shieldValue: 1,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "11",
               key: "tieaggressor",
            },
            "tiebomber":
            {
               name: "TIE Bomber",
               primaryWeaponValue: 2,
               agilityValue: 2,
               hullValue: 6,
               shieldValue: 0,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_HARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_HARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD,
        Maneuver.KOIOGRAN_TURN_5_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BARREL_ROLL],
               wave: "3",
               key: "tiebomber",
            },
            "tiedefender":
            {
               name: "TIE Defender",
               primaryWeaponValue: 3,
               agilityValue: 3,
               hullValue: 3,
               shieldValue: 3,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_HARD, Maneuver.BANK_LEFT_1_STANDARD, Maneuver.BANK_RIGHT_1_STANDARD, Maneuver.TURN_RIGHT_1_HARD,
        Maneuver.TURN_LEFT_2_HARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_HARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_EASY, Maneuver.KOIOGRAN_TURN_4_STANDARD,
        Maneuver.STRAIGHT_5_EASY],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BARREL_ROLL],
               wave: "4",
               key: "tiedefender",
            },
            "tiefighter":
            {
               name: "TIE Fighter",
               primaryWeaponValue: 2,
               agilityValue: 3,
               hullValue: 3,
               shieldValue: 0,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD,
        Maneuver.STRAIGHT_5_STANDARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.BARREL_ROLL, ShipAction.EVADE],
               wave: "0",
               key: "tiefighter",
            },
            "tiefofighter":
            {
               name: "TIE/fo Fighter",
               primaryWeaponValue: 2,
               agilityValue: 3,
               hullValue: 3,
               shieldValue: 1,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_EASY, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_EASY, Maneuver.SEGNORS_LOOP_LEFT_2_HARD, Maneuver.SEGNORS_LOOP_RIGHT_2_HARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD,
        Maneuver.STRAIGHT_5_STANDARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BARREL_ROLL, ShipAction.EVADE],
               wave: "0",
               key: "tiefofighter",
            },
            "tieinterceptor":
            {
               name: "TIE Interceptor",
               primaryWeaponValue: 3,
               agilityValue: 3,
               hullValue: 3,
               shieldValue: 0,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_EASY, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_EASY,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_EASY,
        Maneuver.STRAIGHT_5_STANDARD, Maneuver.KOIOGRAN_TURN_5_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.BARREL_ROLL, ShipAction.BOOST, ShipAction.EVADE],
               wave: "2",
               key: "tieinterceptor",
            },
            "tiephantom":
            {
               name: "TIE Phantom",
               primaryWeaponValue: 4,
               agilityValue: 2,
               hullValue: 2,
               shieldValue: 2,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.BARREL_ROLL, ShipAction.EVADE, ShipAction.CLOAK],
               wave: "4",
               key: "tiephantom",
            },
            "tiepunisher":
            {
               name: "TIE Punisher",
               primaryWeaponValue: 2,
               agilityValue: 1,
               hullValue: 6,
               shieldValue: 3,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_HARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_HARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.KOIOGRAN_TURN_4_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BOOST],
               wave: "7",
               key: "tiepunisher",
            },
            "tiesffighter":
            {
               name: "TIE/sf Fighter",
               primaryWeaponValue: 2,
               agilityValue: 2,
               hullValue: 3,
               shieldValue: 3,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               auxiliaryFiringArcKey: FiringArc.AFT,
               maneuverKeys: [Maneuver.TURN_LEFT_1_HARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_HARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_HARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_HARD, Maneuver.SEGNORS_LOOP_LEFT_3_HARD, Maneuver.SEGNORS_LOOP_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "9",
               key: "tiesffighter",
            },
            "tiesilencer":
            {
               name: "TIE Silencer",
               primaryWeaponValue: 3,
               agilityValue: 3,
               hullValue: 4,
               shieldValue: 2,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_EASY, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_EASY,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_EASY, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_EASY, Maneuver.TURN_RIGHT_3_STANDARD, Maneuver.TALLON_ROLL_LEFT_3_HARD, Maneuver.TALLON_ROLL_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_EASY, Maneuver.KOIOGRAN_TURN_4_HARD,
        Maneuver.STRAIGHT_5_EASY],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.BOOST, ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "13",
               key: "tiesilencer",
            },
            "tiestriker":
            {
               name: "TIE Striker",
               primaryWeaponValue: 3,
               agilityValue: 2,
               hullValue: 4,
               shieldValue: 0,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD, Maneuver.KOIOGRAN_TURN_2_HARD, Maneuver.SEGNORS_LOOP_LEFT_2_HARD, Maneuver.SEGNORS_LOOP_RIGHT_2_HARD,
        Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.EVADE, ShipAction.FOCUS],
               wave: "10",
               key: "tiestriker",
            },
            "upsilonclassshuttle":
            {
               name: "Upsilon-class Shuttle",
               primaryWeaponValue: 4,
               agilityValue: 1,
               hullValue: 6,
               shieldValue: 6,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.STATIONARY_0_HARD,
        Maneuver.TURN_LEFT_1_HARD, Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD, Maneuver.TURN_RIGHT_1_HARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_HARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_HARD],
               shipActionKeys: [ShipAction.COORDINATE, ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "10",
               key: "upsilonclassshuttle",
            },
            "uwing":
            {
               name: "U-Wing",
               primaryWeaponValue: 3,
               agilityValue: 1,
               hullValue: 4,
               shieldValue: 4,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.STATIONARY_0_HARD,
        Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD],
               shipActionKeys: [ShipAction.TARGET_LOCK, ShipAction.FOCUS],
               wave: "10",
               key: "uwing",
            },
            "vcx100":
            {
               name: "VCX-100",
               description: "A VCX-100.",
               primaryWeaponValue: 4,
               agilityValue: 0,
               hullValue: 10,
               shieldValue: 6,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_HARD, Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD, Maneuver.TURN_RIGHT_1_HARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_HARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD,
        Maneuver.KOIOGRAN_TURN_5_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.EVADE, ShipAction.TARGET_LOCK],
               wave: "8",
               wikiUrl: "http://xwing-miniatures.wikia.com/wiki/Ghost_Expansion_Pack",
               key: "vcx100",
            },
            "vt49decimator":
            {
               name: "VT-49 Decimator",
               primaryWeaponValue: 3,
               agilityValue: 0,
               hullValue: 12,
               shieldValue: 4,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               isPrimaryWeaponTurret: true,
               maneuverKeys: [Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_STANDARD, Maneuver.BANK_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "5",
               key: "vt49decimator",
            },
            "xwing":
            {
               name: "X-Wing",
               primaryWeaponValue: 3,
               agilityValue: 2,
               hullValue: 3,
               shieldValue: 2,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "0",
               key: "xwing",
            },
            "yt1300":
            {
               name: "YT-1300",
               description: "A YT-1300.",
               primaryWeaponValue: 3,
               agilityValue: 1,
               hullValue: 8,
               shieldValue: 5,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               isPrimaryWeaponTurret: true,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "2",
               wikiUrl: "http://xwing-miniatures.wikia.com/wiki/Millennium_Falcon_Expansion_Pack",
               key: "yt1300",
            },
            "yt2400":
            {
               name: "YT-2400",
               description: "A YT-2400.",
               primaryWeaponValue: 2,
               agilityValue: 2,
               hullValue: 5,
               shieldValue: 5,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               isPrimaryWeaponTurret: true,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BARREL_ROLL],
               wave: "5",
               wikiUrl: "http://xwing-miniatures.wikia.com/wiki/YT-2400_Freighter_Expansion_Pack",
               key: "yt2400",
            },
            "yv666":
            {
               name: "YV-666",
               description: "A YV-666.",
               primaryWeaponValue: 3,
               agilityValue: 1,
               hullValue: 6,
               shieldValue: 6,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               auxiliaryFiringArcKey: FiringArc.FULL_AFT,
               maneuverKeys: [Maneuver.STATIONARY_0_HARD,
        Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_HARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_HARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "7",
               wikiUrl: "http://xwing-miniatures.wikia.com/wiki/Hound%27s_Tooth_Expansion_Pack",
               key: "yv666",
            },
            "ywing":
            {
               name: "Y-Wing",
               primaryWeaponValue: 2,
               agilityValue: 1,
               hullValue: 5,
               shieldValue: 3,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_HARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_HARD, Maneuver.KOIOGRAN_TURN_4_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "1",
               key: "ywing",
            },
            "z95headhunter":
            {
               name: "Z-95 Headhunter",
               primaryWeaponValue: 2,
               agilityValue: 2,
               hullValue: 2,
               shieldValue: 2,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wave: "4",
               key: "z95headhunter",
            },

            ////////////////////////////////////////////////////////////////////
            // Huge ships.
            "cRocCruiser":
            {
               fore:
               {
                  name: "C-ROC Cruiser (fore)",
                  pilotSkillValue: 1,
                  energyValue: 4,
                  agilityValue: 0,
                  hullValue: 10,
                  shieldValue: 4,
                  shipBaseKey: ShipBase.LARGE,
                  key: "cRocCruiser.fore",
               },
               aft:
               {
                  name: "C-ROC Cruiser (aft)",
                  shipBaseKey: ShipBase.LARGE,
                  key: "cRocCruiser.aft",
               },
               name: "C-ROC Cruiser",
               description: "A C-ROC Cruiser.",
               shipBaseKey: ShipBase.HUGE1,
               maneuverKeys: [Maneuver.BANK_LEFT_1_2, Maneuver.STRAIGHT_1_3, Maneuver.BANK_RIGHT_1_2,
                                Maneuver.BANK_LEFT_2_1, Maneuver.STRAIGHT_2_2, Maneuver.BANK_RIGHT_2_1,
                                Maneuver.STRAIGHT_3_2, Maneuver.STRAIGHT_4_1],
               shipActionKeys: [ShipAction.RECOVER, ShipAction.REINFORCE, ShipAction.TARGET_LOCK, ShipAction.JAM],
               key: "cRocCruiser",
            },
            "cr90Corvette":
            {
               fore:
               {
                  name: "fore",
                  description: "A CR90 Corvette (fore).",
                  pilotSkillValue: 4,
                  primaryWeaponValue: 4,
                  agilityValue: 0,
                  hullValue: 8,
                  shieldValue: 5,
                  shipBaseKey: ShipBase.LARGE,
                  primaryFiringArcKey: FiringArc.FORWARD,
                  isPrimaryWeaponTurret: true,
                  primaryWeaponRanges: [Range.THREE, Range.FOUR, Range.FIVE],
                  shipActionKeys: [ShipAction.COORDINATE, ShipAction.TARGET_LOCK],
                  key: "cr90Corvette.fore",
               },
               aft:
               {
                  name: "aft",
                  description: "A CR90 Corvette (aft).",
                  pilotSkillValue: 4,
                  energyValue: 5,
                  agilityValue: 0,
                  hullValue: 8,
                  shieldValue: 3,
                  shipBaseKey: ShipBase.LARGE,
                  shipActionKeys: [ShipAction.RECOVER, ShipAction.REINFORCE],
                  key: "cr90Corvette.aft",
               },
               crippledFore:
               {
                  name: "crippled fore",
                  description: "A CR90 Corvette (crippled fore).",
                  pilotSkillValue: 4,
                  primaryWeaponValue: 2,
                  shipBaseKey: ShipBase.LARGE,
                  primaryFiringArcKey: FiringArc.FORWARD,
                  isPrimaryWeaponTurret: true,
                  primaryWeaponRanges: [Range.THREE, Range.FOUR, Range.FIVE],
                  shipActionKeys: [],
                  key: "cr90Corvette.crippledFore",
               },
               crippledAft:
               {
                  name: "crippled aft",
                  description: "A CR90 Corvette (crippled aft).",
                  pilotSkillValue: 4,
                  energyValue: 1,
                  shipBaseKey: ShipBase.LARGE,
                  shipActionKeys: [],
                  key: "cr90Corvette.crippledAft",
               },
               name: "CR90 Corvette",
               description: "A CR90 Corvette.",
               shipBaseKey: ShipBase.HUGE2,
               maneuverKeys: [Maneuver.BANK_LEFT_1_3, Maneuver.BANK_RIGHT_1_3, Maneuver.BANK_LEFT_2_2,
                                Maneuver.STRAIGHT_2_3, Maneuver.BANK_RIGHT_2_2, Maneuver.STRAIGHT_3_2,
                                Maneuver.STRAIGHT_4_1],
               key: "cr90Corvette",
            },
            "gozantiClassCruiser":
            {
               fore:
               {
                  name: "Gozanti-class Cruiser (fore)",
                  pilotSkillValue: 2,
                  energyValue: 4,
                  agilityValue: 0,
                  hullValue: 9,
                  shieldValue: 5,
                  shipBaseKey: ShipBase.LARGE,
                  key: "gozantiClassCruiser.fore",
               },
               aft:
               {
                  name: "Gozanti-class Cruiser (aft)",
                  shipBaseKey: ShipBase.LARGE,
                  key: "gozantiClassCruiser.aft",
               },
               name: "Gozanti-class Cruiser",
               description: "A Gozanti-class Cruiser.",
               shipBaseKey: ShipBase.HUGE1,
               maneuverKeys: [Maneuver.BANK_LEFT_1_2, Maneuver.STRAIGHT_1_3, Maneuver.BANK_RIGHT_1_2,
                                Maneuver.BANK_LEFT_2_1, Maneuver.STRAIGHT_2_2, Maneuver.BANK_RIGHT_2_1,
                                Maneuver.STRAIGHT_3_1, Maneuver.STRAIGHT_4_1],
               shipActionKeys: [ShipAction.RECOVER, ShipAction.REINFORCE, ShipAction.COORDINATE,
                                ShipAction.TARGET_LOCK],
               key: "gozantiClassCruiser",
            },
            "gr75MediumTransport":
            {
               fore:
               {
                  name: "GR-75 Medium Transport (fore)",
                  pilotSkillValue: 3,
                  energyValue: 4,
                  agilityValue: 0,
                  hullValue: 8,
                  shieldValue: 4,
                  shipBaseKey: ShipBase.LARGE,
                  key: "gr75MediumTransport.fore",
               },
               aft:
               {
                  name: "GR-75 Medium Transport (aft)",
                  shipBaseKey: ShipBase.LARGE,
                  key: "gr75MediumTransport.aft",
               },
               name: "GR-75 Medium Transport",
               description: "A GR-75 Medium Transport.",
               shipBaseKey: ShipBase.HUGE1,
               maneuverKeys: [Maneuver.BANK_LEFT_1_2, Maneuver.STRAIGHT_1_3, Maneuver.BANK_RIGHT_1_2,
                                Maneuver.BANK_LEFT_2_1, Maneuver.STRAIGHT_2_2, Maneuver.BANK_RIGHT_2_1,
                                Maneuver.STRAIGHT_3_1, Maneuver.STRAIGHT_4_0],
               shipActionKeys: [ShipAction.RECOVER, ShipAction.REINFORCE, ShipAction.COORDINATE,
                                ShipAction.JAM],
               key: "gr75MediumTransport",
            },
            "raiderClassCorvette":
            {
               fore:
               {
                  name: "fore",
                  description: "A Raider-class Corvette (fore).",
                  pilotSkillValue: 4,
                  primaryWeaponValue: 4,
                  agilityValue: 0,
                  hullValue: 8,
                  shieldValue: 6,
                  shipBaseKey: ShipBase.LARGE,
                  primaryFiringArcKey: FiringArc.FORWARD,
                  primaryWeaponRanges: [Range.TWO, Range.THREE, Range.FOUR],
                  shipActionKeys: [ShipAction.RECOVER, ShipAction.REINFORCE],
                  key: "raiderClassCorvette.fore",
               },
               aft:
               {
                  name: "aft",
                  description: "A Raider-class Corvette (aft).",
                  pilotSkillValue: 4,
                  energyValue: 6,
                  agilityValue: 0,
                  hullValue: 8,
                  shieldValue: 4,
                  shipBaseKey: ShipBase.LARGE,
                  shipActionKeys: [ShipAction.COORDINATE, ShipAction.TARGET_LOCK],
                  key: "raiderClassCorvette.aft",
               },
               crippledFore:
               {
                  name: "crippled fore",
                  description: "A Raider-class Corvette (crippled fore).",
                  pilotSkillValue: 4,
                  primaryWeaponValue: 2,
                  shipBaseKey: ShipBase.LARGE,
                  primaryFiringArcKey: FiringArc.FORWARD,
                  primaryWeaponRanges: [Range.TWO, Range.THREE, Range.FOUR],
                  shipActionKeys: [],
                  key: "raiderClassCorvette.crippledFore",
               },
               crippledAft:
               {
                  name: "crippled aft",
                  description: "A Raider-class Corvette (crippled aft).",
                  pilotSkillValue: 4,
                  energyValue: 1,
                  shipBaseKey: ShipBase.LARGE,
                  shipActionKeys: [],
                  key: "raiderClassCorvette.crippledAft",
               },
               name: "Raider-class Corvette",
               description: "A Raider-class Corvette.",
               shipBaseKey: ShipBase.HUGE2,
               maneuverKeys: [Maneuver.BANK_LEFT_1_3, Maneuver.STRAIGHT_1_3, Maneuver.BANK_RIGHT_1_3,
                                Maneuver.BANK_LEFT_2_2, Maneuver.STRAIGHT_2_3, Maneuver.BANK_RIGHT_2_2,
                                Maneuver.STRAIGHT_3_2, Maneuver.STRAIGHT_4_2],
               key: "raiderClassCorvette",
            },
         },
      };

      Ship.keys = function()
      {
         return Object.keys(Ship.properties);
      };

      Ship.values = function()
      {
         return Object.values(Ship.properties);
      };

      Ship.keys().forEach(function(shipKey)
      {
         var ship = Ship.properties[shipKey];
         ship.xwingType = Ship;
         ship.shipBase = ShipBase.properties[ship.shipBaseKey];
         ship.primaryFiringArc = FiringArc.properties[ship.primaryFiringArcKey];
         ship.auxiliaryFiringArc = FiringArc.properties[ship.auxiliaryFiringArcKey];

         if (ship.fore === undefined && ship.primaryWeaponRanges === undefined)
         {
            ship.primaryWeaponRanges = Range.STANDARD_RANGES;
         }

         if (ship.fore)
         {
            ship.fore.xwingType = Ship;
         }

         if (ship.aft)
         {
            ship.aft.xwingType = Ship;
         }
      });

      //////////////////////////////////////////////////////////////////////////
      // Utility methods.

      Ship.toString = function()
      {
         return "Ship";
      };

      if (Object.freeze)
      {
         Object.freeze(Ship);
      }

      return Ship;
   });
