"use strict";

define(["artifact/js/FiringArc", "artifact/js/Maneuver", "artifact/js/Range", "artifact/js/ShipAction", "artifact/js/ShipBase"],
   function(FiringArc, Maneuver, Range, ShipAction, ShipBase)
   {
      var Ship = {
         AGGRESSOR: "aggressor",
         ALPHA_CLASS_STAR_WING: "alphaClassStarWing",
         ARC_170: "arc170",
         ATTACK_SHUTTLE: "attackShuttle",
         AUZITUCK_GUNSHIP: "auzituckGunship",
         A_WING: "aWing",
         B_SF_17_BOMBER: "bSf17Bomber",
         B_WING: "bWing",
         E_WING: "eWing",
         FIRESPRAY_31: "firespray31",
         G_1A_STARFIGHTER: "g1aStarfighter",
         HWK_290: "hwk290",
         JUMP_MASTER_5000: "jumpMaster5000",
         KIHRAXZ_FIGHTER: "kihraxzFighter",
         K_WING: "kWing",
         LAMBDA_CLASS_SHUTTLE: "lambdaClassShuttle",
         LANCER_CLASS_PURSUIT_CRAFT: "lancerClassPursuitCraft",
         M12_L_KIMOGILA_FIGHTER: "m12LKimogilaFighter",
         M3_A_INTERCEPTOR: "m3AInterceptor",
         PROTECTORATE_STARFIGHTER: "protectorateStarfighter",
         QUADJUMPER: "quadjumper",
         SCURRG_H_6_BOMBER: "scurrgH6Bomber",
         SHEATHIPEDE_CLASS_SHUTTLE: "sheathipedeClassShuttle",
         STAR_VIPER: "starViper",
         TIE_ADVANCED: "tieAdvanced",
         TIE_ADVANCED_PROTOTYPE: "tieAdvancedPrototype",
         TIE_AGGRESSOR: "tieAggressor",
         TIE_BOMBER: "tieBomber",
         TIE_DEFENDER: "tieDefender",
         TIE_FIGHTER: "tieFighter",
         TIE_FO_FIGHTER: "tieFoFighter",
         TIE_INTERCEPTOR: "tieInterceptor",
         TIE_PHANTOM: "tiePhantom",
         TIE_PUNISHER: "tiePunisher",
         TIE_SF_FIGHTER: "tieSfFighter",
         TIE_SILENCER: "tieSilencer",
         TIE_STRIKER: "tieStriker",
         T_70_X_WING: "t70XWing",
         UPSILON_CLASS_SHUTTLE: "upsilonClassShuttle",
         U_WING: "uWing",
         VCX_100: "vcx100",
         VT_49_DECIMATOR: "vt49Decimator",
         X_WING: "xWing",
         YT_1300: "yt1300",
         YT_2400: "yt2400",
         YV_666: "yv666",
         Y_WING: "yWing",
         Z_95_HEADHUNTER: "z95Headhunter",

         // Huge ships.
         C_ROC_CRUISER: "cRocCruiser",
         CR90_CORVETTE: "cr90Corvette",
         GOZANTI_CLASS_CRUISER: "gozantiClassCruiser",
         GR_75_MEDIUM_TRANSPORT: "gr75MediumTransport",
         RAIDER_CLASS_CORVETTE: "raiderClassCorvette",

         properties:
         {
            "aWing":
            {
               name: "A-Wing",
               description: "An A-Wing.",
               primaryWeaponValue: 2,
               agilityValue: 3,
               hullValue: 2,
               shieldValue: 2,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_EASY, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_EASY,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_EASY,
        Maneuver.STRAIGHT_5_EASY, Maneuver.KOIOGRAN_TURN_5_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BOOST, ShipAction.EVADE],
               key: "aWing",
            },
            "aggressor":
            {
               name: "Aggressor",
               description: "An Aggressor.",
               primaryWeaponValue: 3,
               agilityValue: 3,
               hullValue: 4,
               shieldValue: 4,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.BANK_LEFT_3_EASY, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_EASY, Maneuver.SEGNORS_LOOP_LEFT_3_HARD, Maneuver.SEGNORS_LOOP_RIGHT_3_HARD,
        Maneuver.KOIOGRAN_TURN_4_HARD
        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BOOST, ShipAction.EVADE],
               wikiUrl: "http://xwing-miniatures.wikia.com/wiki/IG-2000_Expansion_Pack",
               key: "aggressor",
            },
            "alphaClassStarWing":
            {
               name: "Alpha-class Star Wing",
               primaryWeaponValue: 2,
               agilityValue: 2,
               hullValue: 4,
               shieldValue: 3,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_HARD
        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.RELOAD, ShipAction.SLAM, ShipAction.TARGET_LOCK],
               key: "alphaClassStarWing",
            },
            "arc170":
            {
               name: "ARC-170",
               description: "An ARC-170.",
               primaryWeaponValue: 2,
               agilityValue: 1,
               hullValue: 6,
               shieldValue: 3,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               auxiliaryFiringArcKey: FiringArc.AFT,
               maneuverKeys: [Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_HARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_HARD, Maneuver.KOIOGRAN_TURN_4_HARD
        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               key: "arc170",
            },
            "attackShuttle":
            {
               name: "Attack Shuttle",
               description: "An Attack Shuttle.",
               primaryWeaponValue: 3,
               agilityValue: 2,
               hullValue: 2,
               shieldValue: 2,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_HARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_HARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_HARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD
        ],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.EVADE, ShipAction.FOCUS],
               wikiUrl: "http://xwing-miniatures.wikia.com/wiki/Ghost_Expansion_Pack",
               key: "attackShuttle",
            },
            "auzituckGunship":
            {
               name: "Auzituck Gunship",
               primaryWeaponValue: 3,
               agilityValue: 1,
               hullValue: 6,
               shieldValue: 3,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               auxiliaryFiringArcKey: FiringArc.FULL_AFT,
               maneuverKeys: [Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD,
        Maneuver.STRAIGHT_5_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.REINFORCE],
               key: "auzituckGunship",
            },
            "bSf17Bomber":
            {
               name: "B/SF-17 Bomber",
               primaryWeaponValue: 2,
               agilityValue: 1,
               hullValue: 9,
               shieldValue: 3,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.STRAIGHT_0_HARD,
        Maneuver.TURN_LEFT_1_HARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_HARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD

        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               key: "bSf17Bomber",
            },
            "bWing":
            {
               name: "B-Wing",
               description: "A B-Wing.",
               primaryWeaponValue: 3,
               agilityValue: 1,
               hullValue: 3,
               shieldValue: 5,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_HARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_HARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD, Maneuver.KOIOGRAN_TURN_2_HARD,
        Maneuver.BANK_LEFT_3_HARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_HARD
        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BARREL_ROLL],
               key: "bWing",
            },
            "eWing":
            {
               name: "E-Wing",
               description: "An E-Wing.",
               primaryWeaponValue: 3,
               agilityValue: 3,
               hullValue: 2,
               shieldValue: 3,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD,
        Maneuver.STRAIGHT_5_STANDARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BARREL_ROLL, ShipAction.EVADE],
               key: "eWing",
            },
            "firespray31":
            {
               name: "Firespray-31",
               description: "A Firespray-31.",
               primaryWeaponValue: 3,
               agilityValue: 2,
               hullValue: 6,
               shieldValue: 4,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               auxiliaryFiringArcKey: FiringArc.AFT,
               maneuverKeys: [Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD
        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.EVADE],
               wikiUrl: "http://xwing-miniatures.wikia.com/wiki/Slave_1_Expansion_Pack",
               key: "firespray31",
            },
            "g1aStarfighter":
            {
               name: "G-1A Starfighter",
               primaryWeaponValue: 3,
               agilityValue: 1,
               hullValue: 4,
               shieldValue: 4,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_HARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_HARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.BANK_LEFT_3_HARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_HARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD
        ],
               shipActionKeys: [ShipAction.EVADE, ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               key: "g1aStarfighter",
            },
            "hwk290":
            {
               name: "HWK-290",
               description: "An HWK-290.",
               primaryWeaponValue: 1,
               agilityValue: 2,
               hullValue: 4,
               shieldValue: 1,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.BANK_LEFT_3_HARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_HARD
        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               key: "hwk290",
            },
            "jumpMaster5000":
            {
               name: "JumpMaster 5000",
               description: "A JumpMaster 5000.",
               primaryWeaponValue: 2,
               agilityValue: 2,
               hullValue: 5,
               shieldValue: 4,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_EASY, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_EASY, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD, Maneuver.SEGNORS_LOOP_LEFT_2_STANDARD, Maneuver.SEGNORS_LOOP_RIGHT_2_HARD,
        Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD
        ],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wikiUrl: "http://xwing-miniatures.wikia.com/wiki/Punishing_One_Expansion_Pack",
               key: "jumpMaster5000",
            },
            "kWing":
            {
               name: "K-Wing",
               description: "A K-Wing.",
               primaryWeaponValue: 2,
               agilityValue: 1,
               hullValue: 5,
               shieldValue: 4,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD

        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.SLAM],
               key: "kWing",
            },
            "kihraxzFighter":
            {
               name: "Kihraxz Fighter",
               description: "A Kihraxz fighter.",
               primaryWeaponValue: 3,
               agilityValue: 2,
               hullValue: 4,
               shieldValue: 1,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD,
        Maneuver.KOIOGRAN_TURN_5_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               key: "kihraxzFighter",
            },
            "lambdaClassShuttle":
            {
               name: "Lambda-class Shuttle",
               description: "A Lambda-class shuttle.",
               primaryWeaponValue: 3,
               agilityValue: 1,
               hullValue: 5,
               shieldValue: 5,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.STRAIGHT_0_HARD,
        Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_HARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_HARD,
        Maneuver.BANK_LEFT_3_HARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_HARD

        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               key: "lambdaClassShuttle",
            },
            "lancerClassPursuitCraft":
            {
               name: "Lancer-class Pursuit Craft",
               description: "A Lancer-class pursuit craft.",
               primaryWeaponValue: 3,
               agilityValue: 2,
               hullValue: 7,
               shieldValue: 3,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_STANDARD, Maneuver.BANK_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_EASY, Maneuver.BANK_LEFT_3_EASY, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_EASY, Maneuver.TURN_RIGHT_3_EASY,
        Maneuver.STRAIGHT_4_EASY,
        Maneuver.STRAIGHT_5_STANDARD, Maneuver.KOIOGRAN_TURN_5_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.EVADE, ShipAction.ROTATE_ARC, ShipAction.TARGET_LOCK],
               key: "lancerClassPursuitCraft",
            },
            "m12LKimogilaFighter":
            {
               name: "M12-L Kimogila Fighter",
               primaryWeaponValue: 3,
               agilityValue: 1,
               hullValue: 6,
               shieldValue: 2,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_HARD, Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD, Maneuver.TURN_RIGHT_1_HARD,
        Maneuver.TURN_LEFT_2_HARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_HARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.KOIOGRAN_TURN_4_HARD
        ],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.FOCUS, ShipAction.RELOAD, ShipAction.TARGET_LOCK],
               key: "m12LKimogilaFighter",
            },
            "m3AInterceptor":
            {
               name: "M3-A Interceptor",
               description: "An M3-A Interceptor.",
               primaryWeaponValue: 2,
               agilityValue: 3,
               hullValue: 2,
               shieldValue: 1,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD,
        Maneuver.KOIOGRAN_TURN_5_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BARREL_ROLL, ShipAction.EVADE],
               wikiUrl: "http://xwing-miniatures.wikia.com/wiki/M3-A_Scyk_Interceptor_Expansion_Pack",
               key: "m3AInterceptor",
            },
            "protectorateStarfighter":
            {
               name: "Protectorate Starfighter",
               description: "A Protectorate starfighter.",
               primaryWeaponValue: 3,
               agilityValue: 3,
               hullValue: 4,
               shieldValue: 0,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_EASY, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_EASY, Maneuver.TALLON_ROLL_LEFT_2_HARD, Maneuver.TALLON_ROLL_RIGHT_2_HARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD,
        Maneuver.STRAIGHT_5_STANDARD],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.BOOST, ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               key: "protectorateStarfighter",
            },
            "quadjumper":
            {
               name: "Quadjumper",
               primaryWeaponValue: 2,
               agilityValue: 2,
               hullValue: 5,
               shieldValue: 0,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_STANDARD, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD, Maneuver.SEGNORS_LOOP_LEFT_2_HARD, Maneuver.SEGNORS_LOOP_RIGHT_2_HARD,
        Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD

        ],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.FOCUS],
               key: "quadjumper",
            },
            "scurrgH6Bomber":
            {
               name: "Scurrg H-6 Bomber",
               primaryWeaponValue: 3,
               agilityValue: 1,
               hullValue: 5,
               shieldValue: 5,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_HARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_HARD, Maneuver.TALLON_ROLL_LEFT_3_HARD, Maneuver.TALLON_ROLL_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD,
        Maneuver.STRAIGHT_5_HARD],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               key: "scurrgH6Bomber",
            },
            "sheathipedeClassShuttle":
            {
               name: "Sheathipede-class Shuttle",
               primaryWeaponValue: 2,
               agilityValue: 2,
               hullValue: 4,
               shieldValue: 1,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               auxiliaryFiringArcKey: FiringArc.AFT,
               maneuverKeys: [Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_HARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_HARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_HARD
        ],
               shipActionKeys: [ShipAction.COORDINATE, ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               key: "sheathipedeClassShuttle",
            },
            "starViper":
            {
               name: "StarViper",
               description: "A StarViper.",
               primaryWeaponValue: 3,
               agilityValue: 3,
               hullValue: 4,
               shieldValue: 1,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.SEGNORS_LOOP_LEFT_3_HARD, Maneuver.SEGNORS_LOOP_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD
        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BARREL_ROLL, ShipAction.BOOST],
               key: "starViper",
            },
            "t70XWing":
            {
               name: "T-70 X-Wing",
               description: "A T-70 X-Wing.",
               primaryWeaponValue: 3,
               agilityValue: 2,
               hullValue: 3,
               shieldValue: 3,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD, Maneuver.TALLON_ROLL_LEFT_3_HARD, Maneuver.TALLON_ROLL_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD
        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BOOST],
               key: "t70XWing",
            },
            "tieAdvanced":
            {
               name: "TIE Advanced",
               description: "A TIE Advanced.",
               primaryWeaponValue: 2,
               agilityValue: 3,
               hullValue: 3,
               shieldValue: 2,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD,
        Maneuver.STRAIGHT_5_STANDARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BARREL_ROLL, ShipAction.EVADE],
               key: "tieAdvanced",
            },
            "tieAdvancedPrototype":
            {
               name: "TIE Adv. Prototype",
               description: "A TIE Advanced Prototype.",
               primaryWeaponValue: 2,
               agilityValue: 3,
               hullValue: 2,
               shieldValue: 2,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_EASY, Maneuver.BANK_LEFT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_EASY, Maneuver.KOIOGRAN_TURN_4_HARD,
        Maneuver.STRAIGHT_5_STANDARD],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.BOOST, ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wikiUrl: "http://xwing-miniatures.wikia.com/wiki/Inquisitor%27s_TIE_Expansion_Pack",
               key: "tieAdvancedPrototype",
            },
            "tieAggressor":
            {
               name: "TIE Aggressor",
               primaryWeaponValue: 2,
               agilityValue: 2,
               hullValue: 4,
               shieldValue: 1,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD
        ],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               key: "tieAggressor",
            },
            "tieBomber":
            {
               name: "TIE Bomber",
               description: "A TIE bomber.",
               primaryWeaponValue: 2,
               agilityValue: 2,
               hullValue: 6,
               shieldValue: 0,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_HARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_HARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD,
        Maneuver.KOIOGRAN_TURN_5_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BARREL_ROLL],
               key: "tieBomber",
            },
            "tieDefender":
            {
               name: "TIE Defender",
               description: "A TIE defender.",
               primaryWeaponValue: 3,
               agilityValue: 3,
               hullValue: 3,
               shieldValue: 3,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_HARD, Maneuver.BANK_LEFT_1_STANDARD, Maneuver.BANK_RIGHT_1_STANDARD, Maneuver.TURN_RIGHT_1_HARD,
        Maneuver.TURN_LEFT_2_HARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_HARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_EASY, Maneuver.KOIOGRAN_TURN_4_STANDARD,
        Maneuver.STRAIGHT_5_EASY],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BARREL_ROLL],
               key: "tieDefender",
            },
            "tieFighter":
            {
               name: "TIE Fighter",
               description: "A TIE fighter.",
               primaryWeaponValue: 2,
               agilityValue: 3,
               hullValue: 3,
               shieldValue: 0,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD,
        Maneuver.STRAIGHT_5_STANDARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.BARREL_ROLL, ShipAction.EVADE],
               key: "tieFighter",
            },
            "tieFoFighter":
            {
               name: "TIE/fo Fighter",
               description: "A TIE/fo fighter.",
               primaryWeaponValue: 2,
               agilityValue: 3,
               hullValue: 3,
               shieldValue: 1,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_EASY, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_EASY, Maneuver.SEGNORS_LOOP_LEFT_2_HARD, Maneuver.SEGNORS_LOOP_RIGHT_2_HARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD,
        Maneuver.STRAIGHT_5_STANDARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BARREL_ROLL, ShipAction.EVADE],
               key: "tieFoFighter",
            },
            "tieInterceptor":
            {
               name: "TIE Interceptor",
               description: "A TIE interceptor.",
               primaryWeaponValue: 3,
               agilityValue: 3,
               hullValue: 3,
               shieldValue: 0,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_EASY, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_EASY,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_EASY,
        Maneuver.STRAIGHT_5_STANDARD, Maneuver.KOIOGRAN_TURN_5_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.BARREL_ROLL, ShipAction.BOOST, ShipAction.EVADE],
               key: "tieInterceptor",
            },
            "tiePhantom":
            {
               name: "TIE Phantom",
               description: "A TIE phantom.",
               primaryWeaponValue: 4,
               agilityValue: 2,
               hullValue: 2,
               shieldValue: 2,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD
        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.BARREL_ROLL, ShipAction.EVADE, ShipAction.CLOAK],
               key: "tiePhantom",
            },
            "tiePunisher":
            {
               name: "TIE Punisher",
               description: "A TIE punisher.",
               primaryWeaponValue: 2,
               agilityValue: 1,
               hullValue: 6,
               shieldValue: 3,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_HARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_HARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.KOIOGRAN_TURN_4_HARD
        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BOOST],
               key: "tiePunisher",
            },
            "tieSfFighter":
            {
               name: "TIE/sf Fighter",
               description: "A TIE/sf fighter.",
               primaryWeaponValue: 2,
               agilityValue: 2,
               hullValue: 3,
               shieldValue: 3,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               auxiliaryFiringArcKey: FiringArc.AFT,
               maneuverKeys: [Maneuver.TURN_LEFT_1_HARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_HARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_HARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_HARD, Maneuver.SEGNORS_LOOP_LEFT_3_HARD, Maneuver.SEGNORS_LOOP_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD
        ],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               key: "tieSfFighter",
            },
            "tieSilencer":
            {
               name: "TIE Silencer",
               primaryWeaponValue: 3,
               agilityValue: 3,
               hullValue: 4,
               shieldValue: 2,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_EASY, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_EASY,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_EASY, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_EASY, Maneuver.TURN_RIGHT_3_STANDARD, Maneuver.TALLON_ROLL_LEFT_3_HARD, Maneuver.TALLON_ROLL_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_EASY, Maneuver.KOIOGRAN_TURN_4_HARD,
        Maneuver.STRAIGHT_5_EASY],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.BOOST, ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               key: "tieSilencer",
            },
            "tieStriker":
            {
               name: "TIE Striker",
               primaryWeaponValue: 3,
               agilityValue: 2,
               hullValue: 4,
               shieldValue: 0,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD, Maneuver.KOIOGRAN_TURN_2_HARD, Maneuver.SEGNORS_LOOP_LEFT_2_HARD, Maneuver.SEGNORS_LOOP_RIGHT_2_HARD,
        Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD

        ],
               shipActionKeys: [ShipAction.BARREL_ROLL, ShipAction.EVADE, ShipAction.FOCUS],
               key: "tieStriker",
            },
            "uWing":
            {
               name: "U-Wing",
               description: "A U-Wing.",
               primaryWeaponValue: 3,
               agilityValue: 1,
               hullValue: 4,
               shieldValue: 4,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.STRAIGHT_0_HARD,
        Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD
        ],
               shipActionKeys: [ShipAction.TARGET_LOCK, ShipAction.FOCUS],
               key: "uWing",
            },
            "upsilonClassShuttle":
            {
               name: "Upsilon-class Shuttle",
               description: "An Upsilon-class shuttle.",
               primaryWeaponValue: 4,
               agilityValue: 1,
               hullValue: 6,
               shieldValue: 6,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.STRAIGHT_0_HARD,
        Maneuver.TURN_LEFT_1_HARD, Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD, Maneuver.TURN_RIGHT_1_HARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_HARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_HARD

        ],
               shipActionKeys: [ShipAction.COORDINATE, ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               key: "upsilonClassShuttle",
            },
            "vcx100":
            {
               name: "VCX-100",
               description: "A VCX-100.",
               primaryWeaponValue: 4,
               agilityValue: 0,
               hullValue: 10,
               shieldValue: 6,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_HARD, Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD, Maneuver.TURN_RIGHT_1_HARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_HARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD,
        Maneuver.KOIOGRAN_TURN_5_HARD],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.EVADE, ShipAction.TARGET_LOCK],
               wikiUrl: "http://xwing-miniatures.wikia.com/wiki/Ghost_Expansion_Pack",
               key: "vcx100",
            },
            "vt49Decimator":
            {
               name: "VT-49 Decimator",
               description: "A VT-49 Decimator.",
               primaryWeaponValue: 3,
               agilityValue: 0,
               hullValue: 12,
               shieldValue: 4,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_STANDARD, Maneuver.BANK_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD
        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               key: "vt49Decimator",
            },
            "xWing":
            {
               name: "X-Wing",
               description: "An X-Wing.",
               primaryWeaponValue: 3,
               agilityValue: 2,
               hullValue: 3,
               shieldValue: 2,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD
        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               key: "xWing",
            },
            "yWing":
            {
               name: "Y-Wing",
               description: "A Y-Wing.",
               primaryWeaponValue: 2,
               agilityValue: 1,
               hullValue: 5,
               shieldValue: 3,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_HARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_HARD,
        Maneuver.STRAIGHT_4_HARD, Maneuver.KOIOGRAN_TURN_4_HARD
        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               key: "yWing",
            },
            "yt1300":
            {
               name: "YT-1300",
               description: "A YT-1300.",
               primaryWeaponValue: 3,
               agilityValue: 1,
               hullValue: 8,
               shieldValue: 5,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD
        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wikiUrl: "http://xwing-miniatures.wikia.com/wiki/Millennium_Falcon_Expansion_Pack",
               key: "yt1300",
            },
            "yt2400":
            {
               name: "YT-2400",
               description: "A YT-2400.",
               primaryWeaponValue: 2,
               agilityValue: 2,
               hullValue: 5,
               shieldValue: 5,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.TURN_LEFT_1_STANDARD, Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY, Maneuver.TURN_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD, Maneuver.KOIOGRAN_TURN_4_HARD
        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK, ShipAction.BARREL_ROLL],
               wikiUrl: "http://xwing-miniatures.wikia.com/wiki/YT-2400_Freighter_Expansion_Pack",
               key: "yt2400",
            },
            "yv666":
            {
               name: "YV-666",
               description: "A YV-666.",
               primaryWeaponValue: 3,
               agilityValue: 1,
               hullValue: 6,
               shieldValue: 6,
               shipBaseKey: ShipBase.LARGE,
               primaryFiringArcKey: FiringArc.FORWARD,
               auxiliaryFiringArcKey: FiringArc.FULL_AFT,
               maneuverKeys: [Maneuver.STRAIGHT_0_HARD,
        Maneuver.BANK_LEFT_1_EASY, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_EASY,
        Maneuver.TURN_LEFT_2_HARD, Maneuver.BANK_LEFT_2_STANDARD, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_STANDARD, Maneuver.TURN_RIGHT_2_HARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_EASY, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD,
        Maneuver.STRAIGHT_4_STANDARD
        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               wikiUrl: "http://xwing-miniatures.wikia.com/wiki/Hound%27s_Tooth_Expansion_Pack",
               key: "yv666",
            },
            "z95Headhunter":
            {
               name: "Z-95 Headhunter",
               description: "A Z-95 headhunter.",
               primaryWeaponValue: 2,
               agilityValue: 2,
               hullValue: 2,
               shieldValue: 2,
               shipBaseKey: ShipBase.SMALL,
               primaryFiringArcKey: FiringArc.FORWARD,
               maneuverKeys: [Maneuver.BANK_LEFT_1_STANDARD, Maneuver.STRAIGHT_1_EASY, Maneuver.BANK_RIGHT_1_STANDARD,
        Maneuver.TURN_LEFT_2_STANDARD, Maneuver.BANK_LEFT_2_EASY, Maneuver.STRAIGHT_2_EASY, Maneuver.BANK_RIGHT_2_EASY, Maneuver.TURN_RIGHT_2_STANDARD,
        Maneuver.TURN_LEFT_3_STANDARD, Maneuver.BANK_LEFT_3_STANDARD, Maneuver.STRAIGHT_3_STANDARD, Maneuver.BANK_RIGHT_3_STANDARD, Maneuver.TURN_RIGHT_3_STANDARD, Maneuver.KOIOGRAN_TURN_3_HARD,
        Maneuver.STRAIGHT_4_STANDARD
        ],
               shipActionKeys: [ShipAction.FOCUS, ShipAction.TARGET_LOCK],
               key: "z95Headhunter",
            },

            ////////////////////////////////////////////////////////////////////
            // Huge ships.
            "cRocCruiser":
            {
               fore:
               {
                  name: "C-ROC Cruiser (fore)",
                  pilotSkillValue: 1,
                  energyValue: 4,
                  agilityValue: 0,
                  hullValue: 10,
                  shieldValue: 4,
                  shipBaseKey: ShipBase.LARGE,
                  key: "cRocCruiser.fore",
               },
               aft:
               {
                  name: "C-ROC Cruiser (aft)",
                  shipBaseKey: ShipBase.LARGE,
                  key: "cRocCruiser.aft",
               },
               name: "C-ROC Cruiser",
               description: "A C-ROC Cruiser.",
               shipBaseKey: ShipBase.HUGE1,
               maneuverKeys: [Maneuver.BANK_LEFT_1_2, Maneuver.STRAIGHT_1_3, Maneuver.BANK_RIGHT_1_2,
                                Maneuver.BANK_LEFT_2_1, Maneuver.STRAIGHT_2_2, Maneuver.BANK_RIGHT_2_1,
                                Maneuver.STRAIGHT_3_2, Maneuver.STRAIGHT_4_1],
               shipActionKeys: [ShipAction.RECOVER, ShipAction.REINFORCE, ShipAction.TARGET_LOCK, ShipAction.JAM],
               key: "cRocCruiser",
            },
            "cr90Corvette":
            {
               fore:
               {
                  name: "fore",
                  description: "A CR90 Corvette (fore).",
                  pilotSkillValue: 4,
                  primaryWeaponValue: 4,
                  agilityValue: 0,
                  hullValue: 8,
                  shieldValue: 5,
                  shipBaseKey: ShipBase.LARGE,
                  primaryFiringArcKey: FiringArc.FORWARD,
                  isPrimaryWeaponTurret: true,
                  primaryWeaponRanges: [Range.THREE, Range.FOUR, Range.FIVE],
                  shipActionKeys: [ShipAction.COORDINATE, ShipAction.TARGET_LOCK],
                  key: "cr90Corvette.fore",
               },
               aft:
               {
                  name: "aft",
                  description: "A CR90 Corvette (aft).",
                  pilotSkillValue: 4,
                  energyValue: 5,
                  agilityValue: 0,
                  hullValue: 8,
                  shieldValue: 3,
                  shipBaseKey: ShipBase.LARGE,
                  shipActionKeys: [ShipAction.RECOVER, ShipAction.REINFORCE],
                  key: "cr90Corvette.aft",
               },
               crippledFore:
               {
                  name: "crippled fore",
                  description: "A CR90 Corvette (crippled fore).",
                  pilotSkillValue: 4,
                  primaryWeaponValue: 2,
                  shipBaseKey: ShipBase.LARGE,
                  primaryFiringArcKey: FiringArc.FORWARD,
                  isPrimaryWeaponTurret: true,
                  primaryWeaponRanges: [Range.THREE, Range.FOUR, Range.FIVE],
                  shipActionKeys: [],
                  key: "cr90Corvette.crippledFore",
               },
               crippledAft:
               {
                  name: "crippled aft",
                  description: "A CR90 Corvette (crippled aft).",
                  pilotSkillValue: 4,
                  energyValue: 1,
                  shipBaseKey: ShipBase.LARGE,
                  shipActionKeys: [],
                  key: "cr90Corvette.crippledAft",
               },
               name: "CR90 Corvette",
               description: "A CR90 Corvette.",
               shipBaseKey: ShipBase.HUGE2,
               maneuverKeys: [Maneuver.BANK_LEFT_1_3, Maneuver.BANK_RIGHT_1_3, Maneuver.BANK_LEFT_2_2,
                                Maneuver.STRAIGHT_2_3, Maneuver.BANK_RIGHT_2_2, Maneuver.STRAIGHT_3_2,
                                Maneuver.STRAIGHT_4_1],
               key: "cr90Corvette",
            },
            "gozantiClassCruiser":
            {
               fore:
               {
                  name: "Gozanti-class Cruiser (fore)",
                  pilotSkillValue: 2,
                  energyValue: 4,
                  agilityValue: 0,
                  hullValue: 9,
                  shieldValue: 5,
                  shipBaseKey: ShipBase.LARGE,
                  key: "gozantiClassCruiser.fore",
               },
               aft:
               {
                  name: "Gozanti-class Cruiser (aft)",
                  shipBaseKey: ShipBase.LARGE,
                  key: "gozantiClassCruiser.aft",
               },
               name: "Gozanti-class Cruiser",
               description: "A Gozanti-class Cruiser.",
               shipBaseKey: ShipBase.HUGE1,
               maneuverKeys: [Maneuver.BANK_LEFT_1_2, Maneuver.STRAIGHT_1_3, Maneuver.BANK_RIGHT_1_2,
                                Maneuver.BANK_LEFT_2_1, Maneuver.STRAIGHT_2_2, Maneuver.BANK_RIGHT_2_1,
                                Maneuver.STRAIGHT_3_1, Maneuver.STRAIGHT_4_1],
               shipActionKeys: [ShipAction.RECOVER, ShipAction.REINFORCE, ShipAction.COORDINATE,
                                ShipAction.TARGET_LOCK],
               key: "gozantiClassCruiser",
            },
            "gr75MediumTransport":
            {
               fore:
               {
                  name: "GR-75 Medium Transport (fore)",
                  pilotSkillValue: 3,
                  energyValue: 4,
                  agilityValue: 0,
                  hullValue: 8,
                  shieldValue: 4,
                  shipBaseKey: ShipBase.LARGE,
                  key: "gr75MediumTransport.fore",
               },
               aft:
               {
                  name: "GR-75 Medium Transport (aft)",
                  shipBaseKey: ShipBase.LARGE,
                  key: "gr75MediumTransport.aft",
               },
               name: "GR-75 Medium Transport",
               description: "A GR-75 Medium Transport.",
               shipBaseKey: ShipBase.HUGE1,
               maneuverKeys: [Maneuver.BANK_LEFT_1_2, Maneuver.STRAIGHT_1_3, Maneuver.BANK_RIGHT_1_2,
                                Maneuver.BANK_LEFT_2_1, Maneuver.STRAIGHT_2_2, Maneuver.BANK_RIGHT_2_1,
                                Maneuver.STRAIGHT_3_1, Maneuver.STRAIGHT_4_0],
               shipActionKeys: [ShipAction.RECOVER, ShipAction.REINFORCE, ShipAction.COORDINATE,
                                ShipAction.JAM],
               key: "gr75MediumTransport",
            },
            "raiderClassCorvette":
            {
               fore:
               {
                  name: "fore",
                  description: "A Raider-class Corvette (fore).",
                  pilotSkillValue: 4,
                  primaryWeaponValue: 4,
                  agilityValue: 0,
                  hullValue: 8,
                  shieldValue: 6,
                  shipBaseKey: ShipBase.LARGE,
                  primaryFiringArcKey: FiringArc.FORWARD,
                  primaryWeaponRanges: [Range.TWO, Range.THREE, Range.FOUR],
                  shipActionKeys: [ShipAction.RECOVER, ShipAction.REINFORCE],
                  key: "raiderClassCorvette.fore",
               },
               aft:
               {
                  name: "aft",
                  description: "A Raider-class Corvette (aft).",
                  pilotSkillValue: 4,
                  energyValue: 6,
                  agilityValue: 0,
                  hullValue: 8,
                  shieldValue: 4,
                  shipBaseKey: ShipBase.LARGE,
                  shipActionKeys: [ShipAction.COORDINATE, ShipAction.TARGET_LOCK],
                  key: "raiderClassCorvette.aft",
               },
               crippledFore:
               {
                  name: "crippled fore",
                  description: "A Raider-class Corvette (crippled fore).",
                  pilotSkillValue: 4,
                  primaryWeaponValue: 2,
                  shipBaseKey: ShipBase.LARGE,
                  primaryFiringArcKey: FiringArc.FORWARD,
                  primaryWeaponRanges: [Range.TWO, Range.THREE, Range.FOUR],
                  shipActionKeys: [],
                  key: "raiderClassCorvette.crippledFore",
               },
               crippledAft:
               {
                  name: "crippled aft",
                  description: "A Raider-class Corvette (crippled aft).",
                  pilotSkillValue: 4,
                  energyValue: 1,
                  shipBaseKey: ShipBase.LARGE,
                  shipActionKeys: [],
                  key: "raiderClassCorvette.crippledAft",
               },
               name: "Raider-class Corvette",
               description: "A Raider-class Corvette.",
               shipBaseKey: ShipBase.HUGE2,
               maneuverKeys: [Maneuver.BANK_LEFT_1_3, Maneuver.STRAIGHT_1_3, Maneuver.BANK_RIGHT_1_3,
                                Maneuver.BANK_LEFT_2_2, Maneuver.STRAIGHT_2_3, Maneuver.BANK_RIGHT_2_2,
                                Maneuver.STRAIGHT_3_2, Maneuver.STRAIGHT_4_2],
               key: "raiderClassCorvette",
            },
         },
      };

      Ship.keys = function()
      {
         return Object.keys(Ship.properties);
      };

      Ship.values = function()
      {
         return Object.values(Ship.properties);
      };

      Ship.keys().forEach(function(shipKey)
      {
         var ship = Ship.properties[shipKey];
         ship.xwingType = Ship;
         ship.shipBase = ShipBase.properties[ship.shipBaseKey];
         ship.primaryFiringArc = FiringArc.properties[ship.primaryFiringArcKey];
         ship.auxiliaryFiringArc = FiringArc.properties[ship.auxiliaryFiringArcKey];

         if (ship.fore === undefined && ship.primaryWeaponRanges === undefined)
         {
            ship.primaryWeaponRanges = Range.STANDARD_RANGES;
         }

         if (ship.fore)
         {
            ship.fore.xwingType = Ship;
         }

         if (ship.aft)
         {
            ship.aft.xwingType = Ship;
         }
      });

      //////////////////////////////////////////////////////////////////////////
      // Utility methods.

      Ship.toString = function()
      {
         return "Ship";
      };

      if (Object.freeze)
      {
         Object.freeze(Ship);
      }

      return Ship;
   });
